### ISSUE TITLE
doesn't work with L5.3

### ISSUE THREAD

**Issue by scasic** [squareboat/sneaker#1]
could you please update package for Laravel 5.3?

**Comment by akaamitgupta** [comment]
The package works with L5.3. Can you provide more detail about the error so that we can help you?

**Comment by jsartisan** [comment]
@scasic it works perfectly fine on Laravel 5.3. You might have not set SNEAKER_SILENT in your .env  to false. The package comes with default SNEAKER_SILENT value as true. So it might not be firing off any emails.

**Comment by scasic** [comment]
it works now after reinstalling package. 
thanks!
