### ISSUE TITLE
Always sending 2 emails

### ISSUE THREAD

**Issue by sweebee** [squareboat/sneaker#12]
Sneaker always sends me a duplicate error message. I'm using Laravel 5.4.

This is all i have in the exception handler:

```php
public function report(Exception $exception)
    {
	    app('sneaker')->captureException($exception);
        parent::report($exception);
    }
```

**Comment by akaamitgupta** [comment]
@sweebee Not sure why it's happening. I am using Senaker with multiple projects and never seen this.
Can you try it with a new Laravel project and see if it's happening again?

**Comment by sweebee** [comment]
Don't know why but on the production server it works fine, but locally it sends double. It happens on multiple laravel projects. But not a problem since i don't need an email on the local testing env.

**Comment by akaamitgupta** [comment]
Ok great. Closing it for now.
