### ISSUE TITLE
All errors except..

### ISSUE THREAD

**Issue by sweebee** [squareboat/sneaker#13]
is it possible to capture all errors except some?

I'm also getting NotFoundHttpException and VerifyCsrfToken errors.

In the Exceptionhandler they are in the don't report variable, but sneaker does still send them.

I do it now in the report function, but would be nice to configure this in the sneaker config.

```php
protected $dontReport = [
		\Illuminate\Auth\AuthenticationException::class,
		\Illuminate\Auth\Access\AuthorizationException::class,
		\Symfony\Component\HttpKernel\Exception\HttpException::class,
		\Illuminate\Database\Eloquent\ModelNotFoundException::class,
		\Illuminate\Session\TokenMismatchException::class,
		\Illuminate\Validation\ValidationException::class,
		\Illuminate\Contracts\Encryption\DecryptException::class,
		\Symfony\Component\HttpKernel\Exception\NotFoundHttpException::class
	];

	public function report(Exception $exception)
	{
		if (!$exception instanceof NotFoundHttpException and !$exception instanceof TokenMismatchException) {
			app('sneaker')->captureException($exception);
		}
		parent::report($exception);
	}
```

**Comment by akaamitgupta** [comment]
@sweebee You can do this easily. Just follow the readme.

For reference - https://github.com/squareboat/sneaker#capture

**Comment by hrkut** [comment]
No, you can do it in the config. @sweebee means add to config an option like 'dont_capture' and specify there  all exceptions you don't want to capture all others will be captured. I will be very handy for me as well. Thank you.
