### ISSUE TITLE
Getting an email about different domain.

### ISSUE THREAD

**Issue by kushal555** [squareboat/sneaker#14]
Really unbelievable, 
I set up your library in my local project and configure my mailtrap account. Now I create a dummy route in which I set some error. Now I am hitting that URL into browser then I am getting the email which has different content which saying request URL:-  http://vocalhealth.org/wp-login.php
![image](https://user-images.githubusercontent.com/8221746/31663494-ee82407a-b35f-11e7-8ffc-a32428cc942c.png)

Now I am getting continuously email from that domain. I really don't know what happened.

**Comment by kushal555** [comment]
Now I am frequently getting email from different domain in my inbox 
http://wpad.nyee.org/wpad.dat
http://www.vocalhealth.org/feed

Why these domain pointing my website.
@gauravgupta123

**Comment by akaamitgupta** [comment]
@kushal555 Closing this issue for now. If you are facing the issue again then feel free to open it.
