### ISSUE TITLE
Hide stack traces for PDO Exceptions

### ISSUE THREAD

**Issue by mmollick** [squareboat/sneaker#15]
If a PDOException is thrown (database timeout or a connection error), the resulting stack trace will contain the database credentials. It's probably a good idea to add the option to hide the stack trace for these kinds of exceptions to prevent sensitive credentials from being sent to an inbox.

**Comment by akaamitgupta** [comment]
@mmollick Sorry for the extremely late reply.

This is a good idea to be implemented in the package. But I am not getting enough time to follow all requests. I request you for a PR if possible :)
