### ISSUE TITLE
Problem in catch when the return is json response

### ISSUE THREAD

**Issue by sobhanattar** [squareboat/sneaker#19]
Hi
I have this code:
```
public function index(): JsonResponse
{
    try {
        //make some error
       return response()->json(['data' => $data]);
   } catch (Exception $e) {
        return response()->json(['message' => trans('code_execution_fail', ['e' => $e->getCode()])], 422);
   }
}
```

I set `capture` to `'*'` so it get all exceptions. But it doesn't call `report` function in this context although  when I use a function like `abort(404, 'message')` it executes `sneaker` in `report` function and send email to my inbox.

What I'm missing?

**Comment by sobhanattar** [comment]
Hi
I dig dipper and I understood that by returning `json response` no exception throws like the function `abort()` do. So I changed my code to something like this and add finally to email the exception.

```
public function index(): JsonResponse
{
    try {
        //make some error
       return response()->json(['data' => $data]);
   } catch (Exception $e) {
        return response()->json(['message' => trans('code_execution_fail', ['e' => $e->getCode()])], 422);
   } finally {
        isset($e) && $e instanceof Exception && app('sneaker')->captureException($e);
  }
}
```

But this way I have to add `finally` to all my functions. Is there any better way for that?

**Comment by akaamitgupta** [comment]
@sobhanattar Ideally your `App/Exceptions/Handler@report` should be called for each exception but here you are catching each exception by `try {} catch {}` so this is the only solution I can see.

**Comment by sobhanattar** [comment]
@akaamitgupta I found a new solution for this problem, although the change in catch is still a necessity but I'm using a helper method `report($e)` which is short and this way If I want to do some change in the behavior of types of emails and such a things I shouldn't go back and put all that logic in every `catch` blocks which is a + for me.

I think it's not bad to change the Doc to mention this :-)
