### ISSUE TITLE
L5.3 Symfony/debug 3.1.* required, Sneaker requires  Symfony/debug 3.2.*

### ISSUE THREAD

**Issue by daHyperion** [squareboat/sneaker#2]
As described in the title, I cannot install the package since Symfony/debug 3.1.* is required by laravel. What should I do?

**Comment by akaamitgupta** [comment]
@daHyperion Which Laravel you are using?

**Comment by daHyperion** [comment]
Laravel Framework version 5.3.30

**Comment by akaamitgupta** [comment]
@daHyperion Thanks for reporting the issue. I have added the support for symfony/debug - 3.1* and pushed a new release. Can you try to install it again?

**Comment by daHyperion** [comment]
Thank you very much, it worked.
