### ISSUE TITLE
Add support for Laravel 5.8

### ISSUE THREAD

**Issue by Sh1d0w** [squareboat/sneaker#33]

**Comment by andrey-helldar** [comment]
@Sh1d0w, the developer of this package rarely makes changes to the code, so I wrote my own with advanced features.
Your problem is solved in [andrey-helldar/notify-exceptions](https://github.com/andrey-helldar/notify-exceptions) (Laravel 5.8 supported).

**Comment by akaamitgupta** [comment]
@Sh1d0w Will add the support on weekend.

**Comment by andrey-helldar** [comment]
@squareboat, 😛

**Comment by akaamitgupta** [comment]
@Sh1d0w Added the support for Laravel 5.8
