### ISSUE TITLE
Error sending mail: "Illuminate\Mail\SendQueuedMailable::handle(): The script tried to execute a method or access a property of an incomplete object"

### ISSUE THREAD

**Issue by adiafora** [squareboat/sneaker#38]
Hi, when I run the command $ `php artisan sneaker:sneak` , periodically it does not work, but instead there is an error in the logs:
`Illuminate\Mail\SendQueuedMailable::handle(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "SquareBoat\Sneaker\ExceptionMailer" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition`

I run again - works correctly. 

What's the reason? I use Larevel 5.5

Thanks

**Comment by akaamitgupta** [comment]
@adiafora I just installed the new version, tested it again and it worked. Not sure about this error and don't look directly related to this package.

**Comment by adiafora** [comment]
Thanks, everything works perfectly. The mistake just confused me.
