### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by suzonraj** [squareboat/sneaker#41]
Please update to support Laravel 6

**Comment by akaamitgupta** [comment]
@suzonraj Support for Laravel 6 has been already added.

**Comment by suzonraj** [comment]
@akaamitgupta but composer is failed to resolve it for Laravel 6.2.0

**Comment by akaamitgupta** [comment]
@suzonraj Ok. Got it now. I will update the composer file after the checking the change log if there is no breaking changes.

Submitting a PR is also appreciated.

**Comment by bryanrscott** [comment]
#45

**Comment by tommiekn** [comment]
@akaamitgupta updates on this one? it fails on laravel 6.2/6.5

**Comment by akaamitgupta** [comment]
Done.
