### ISSUE TITLE
The except parameter in config/sneaker.php to keep unrequired exceptions outside

### ISSUE THREAD

**Issue by alihuseyn** [squareboat/sneaker#44]
Is it possible to add `except` parameter to the configuration file allow all exceptions in `capture` within the format like below to keeping some exceptions outside of sneaker mail send?

```php
'capture' => [
     '*'
 ],
'except' => [
  Illuminate\Session\TokenMismatchException::class
]
```

**Comment by akaamitgupta** [comment]
In your `App\Exceptions\Handler` file there is an attribute named `dontReport` which can be used to what you require.

And in your report method it can be used as
```
if ($this->shouldReport($exception)) {
    app('sneaker')->captureException($exception);
}
```
