### ISSUE TITLE
Specifying email address in .env

### ISSUE THREAD

**Issue by bilogic** [squareboat/sneaker#50]
Hi,

I'm curious why not allow specifying the email address in .env file?
If it is due to multiple email addresses, perhaps can consider the format below

```
L0_SNEAKER_EMAIL=a1@b.com
L1_SNEAKER_EMAIL=a2@b.com
Lx_SNEAKER_EMAIL=a3@b.com
```

Thanks!

**Comment by akaamitgupta** [comment]
@bilogic 

You can do something in `config/sneaker.php`
```
'to' => explode(',', env('SNEAKER_EMAILS')),
```

and in `.env`
```
SNEAKER_EMAILS=a1@b.com,a2@b.com,a3@b.com
```

**Comment by bilogic** [comment]
@akaamitgupta what I meant was, ```SNEAKER_SILENT``` reads from ```.env``` by default, why doesn't ```SNEAKER_EMAIL``` do the same?

**Comment by akaamitgupta** [comment]
@bilogic 
`config/sneaker.php` is under your control you can update it as you require.

**Comment by bilogic** [comment]
@akaamitgupta i'm merely trying to provide a suggestion for improvement

**Comment by akaamitgupta** [comment]
Thanks @bilogic... really appreciate this. Will look into this in the next release.
