### ISSUE TITLE
Add support Laravel 7

### ISSUE THREAD

**Issue by yagrasdemonde** [squareboat/sneaker#51]
Please, add support for Laravel 7

**Comment by insign** [comment]
I recommend change that bunch of version to > and <

**Comment by jcsoriano** [comment]
There's a PR for it but it hasn't been merged yet: https://github.com/squareboat/sneaker/pull/52

Hope it can be merged soon, also need Laravel 7 support

**Comment by tanmaymohan** [comment]
#52 has been merged. Thanks..!!

Documentation has been updated
