### ISSUE TITLE
Error Email Not Working

### ISSUE THREAD

**Issue by nitin19srivastava** [squareboat/sneaker#6]
hi guys,

Error Email are not working.

My Configuration are - 

Laravel Version - 5.4

app -> exceptions - > handler.php

public function report(Exception $exception)
    {
        if ($this->shouldReport($exception)) {
            app('sneaker')->captureException($exception);
        }
       
        parent::report($exception);
    }

env file ->

                SNEAKER_SILENT=false

                APP_DEBUG=true

                APP_LOG=daily
                APP_LOG_LEVEL=debug

                APP_ENV=local

config -> sneaker.php -

                'capture' => [ '*' ]

                'to' => [ 'nitin@***.net',],

Using CMD to Test - > Message Coming - Sneaker is working Fine.

**Comment by akaamitgupta** [comment]
@nitin19srivastava  All the configuration looks good to me here.

Have you checked the `laravel.log` file for any errors? Also please clear your config cache by `php artisan config:clear` then try again.

And are you able to send normal emails from your app?

**Comment by nitin19srivastava** [comment]
@akaamitgupta 

i did - 
    php artisan config:clear
    php artisan cache:clear
    composer.phar dump-autoload

Normal Email are getting delivered.  

Nothing in Laravel Log.

**Comment by nitin19srivastava** [comment]
@akaamitgupta 

i did - 
    php artisan config:clear
    php artisan cache:clear
    composer.phar dump-autoload

Normal Email are getting delivered.  

Nothing in Laravel Log.

**Comment by nitin19srivastava** [comment]
@akaamitgupta 

now i am getting the error email generated by Laravel if there is any problem in developer's code.

But  when using -  php artisan sneaker:sneak from cmd, i am not getting any error email.

**Comment by akaamitgupta** [comment]
@nitin19srivastava Is it resolved? If yes, what was the problem?

**Comment by nitin19srivastava** [comment]
Yes it is resolved, problem was in my code with Mail Driver .   Error Email are working.   But when using cmd for test, then email is not coming.
